export const HANDLE_QUANTITY = 'HANDLE_QUANTITY';
export const HANDLE_ADD_TO_CART_QUANTITY = 'HANDLE_ADD_TO_CART_QUANTITY';
export const BUY_NOW = 'BUY_NOW';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const DELETE_ALL_PRODUCTS_FROM_CART = 'DELETE_ALL_PRODUCTS_FROM_CART';