export const LOGIN = 'LOGIN';
export const USER = 'USER';
export const REGISTER = 'REGISTER';
export const GET_USER_PROFILE_INFORMATION = 'GET_USER_PROFILE_INFORMATION';
export const UPDATE_USER_PROFILE_INFORMATION = 'UPDATE_USER_PROFILE_INFORMATION';