export const GET_PRODUCT_LIST_BY_CATEGORY_ID = "GET_PRODUCT_LIST_BY_CATEGORY_ID";
export const GET_PRODUCT_LIST_LENGTH_BY_CATEGORY_ID = "GET_PRODUCT_LIST_LENGTH_BY_CATEGORY_ID";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
