export const GET_PRODUCT_LIST_BY_CATEGORY_ID = "GET_PRODUCT_LIST_BY_CATEGORY_ID";
export const GET_PRODUCT_LIST_LENGTH_BY_CATEGORY_ID = "GET_PRODUCT_LIST_LENGTH_BY_CATEGORY_ID";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const UPDATE_STAR_RATE = "UPDATE_STAR_RATE";