export const GET_ALL_PROVINCES = "GET_ALL_PROVINCES";
export const GET_ALL_DISTRICTS_BY_PROVINCE_ID = "GET_ALL_DISTRICTS_BY_PROVINCE_ID";
export const GET_ALL_WARDS_BY_DISTRICT_ID = "GET_ALL_WARDS_BY_DISTRICT_ID";